//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeLightBible
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PlanoLeitura> PlanoLeitura { get; set; }
        public virtual DbSet<RespostasCache> RespostasCache { get; set; }
        public virtual DbSet<UltimoPontoLeitura> UltimoPontoLeitura { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<VersiculoAnotado> VersiculoAnotado { get; set; }
        public virtual DbSet<VersiculoSalvo> VersiculoSalvo { get; set; }
        public virtual DbSet<VersiculoSublinhado> VersiculoSublinhado { get; set; }
    }
}
