//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeLightBible
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanoLeituraDia
    {
        public int Id { get; set; }
        public int PlanoUtilizadorId { get; set; }
        public int Dia { get; set; }
        public string Capitulos { get; set; }
        public Nullable<bool> Lido { get; set; }
        public Nullable<System.DateTime> DataLeitura { get; set; }
    
        public virtual PlanoLeituraUtilizador PlanoLeituraUtilizador { get; set; }
    }
}
