//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeLightBible
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanoLeituraModeloDia
    {
        public int Id { get; set; }
        public int PlanoLeituraId { get; set; }
        public int Dia { get; set; }
        public string Capitulos { get; set; }
    
        public virtual PlanoLeitura PlanoLeitura { get; set; }
    }
}
