//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeLightBible
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanoLeituraUtilizador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanoLeituraUtilizador()
        {
            this.PlanoLeituraDia = new HashSet<PlanoLeituraDia>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int PlanoLeituraId { get; set; }
        public System.DateTime DataInicio { get; set; }
        public Nullable<int> ProgressoDiaAtual { get; set; }
    
        public virtual PlanoLeitura PlanoLeitura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanoLeituraDia> PlanoLeituraDia { get; set; }
        public virtual Users Users { get; set; }
    }
}
