//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeLightBible
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersiculoSublinhado
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Livro { get; set; }
        public int Capitulo { get; set; }
        public int Versiculo { get; set; }
        public string Cor { get; set; }
        public Nullable<System.DateTime> DataCriado { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
